module.exports = {

    // user: require('../app/models/user.server.model'),
    assets: require('../app/models/assets.server.model'),
    ble: require('../app/models/ble.server.model'),
    bookingDetails: require('../app/models/bookingDetails.server.model'),
    building: require('../app/models/building.server.model'),
    dummy: require('../app/models/dummy.server.model'),
    employees: require('../app/models/employees.server.model'),
    excelAggregation: require('../app/models/excelAggregation.server.model'),
    floors: require('../app/models/floors.server.model'),
    hostLog: require('../app/models/hostLogs.server.model'),
    host: require('../app/models/hosts.server.model'),
    lights: require('../app/models/lights.server.model'),
    lightSensors: require('../app/models/lightSensors.server.model'),
    lightSensorToBle: require('../app/models/lightSensorToBle.server.model'),
    lightshapes: require('../app/models/lightshapes.server.model'),
    lightToBle: require('../app/models/lightToBle.server.model'),
    lighttypes: require('../app/models/lighttypes.server.model'),
    lockerRooms: require('../app/models/lockerRooms.server.model'),
    occAggregation: require('../app/models/occAggregation.server.model'),
    parking: require('../app/models/parking.server.model'),
    roomToBle: require('../app/models/roomToBle.server.model'),
    scenes: require('../app/models/scenes.server.model'),
    sceneToLight: require('../app/models/sceneToLight.server.model'),
    scheduler: require('../app/models/scheduler.server.model'),
    schedules: require('../app/models/schedules.server.model'),
    scheduleToLight: require('../app/models/scheduleToLight.server.model'),
    seats: require('../app/models/seats.server.model'),
    seatsettings: require('../app/models/seatsettings.server.model'),
    seattypes: require('../app/models/seattypes.server.model'),
    sections: require('../app/models/sections.server.model'),
    sensorData: require('../app/models/sensorData.server.model'),
    sensorHealthLog: require('../app/models/sensorHealthLog.server.model'),
    sensorToBle: require('../app/models/sensorToBle.server.model'),
    shapes: require('../app/models/shapes.server.model'),
    shifts: require('../app/models/shifts.server.model'),
    site: require('../app/models/site.server.model'),
    zones: require('../app/models/zones.server.model'),
    authtokens: require('../app/models/authtokens.server.model'),
    segments: require('../app/models/segments.server.model'),
    segmentToBle: require('../app/models/segmentToBle.server.model'),


    // customer: require('../app/models/customer.server.model')

};
